#!/bin/sh
echo "Configurando a interface de rede"

ip link set lo up

INTERFACE=$(ip -o link show | awk -F': ' '$2 != "lo" {print $2; exit}')

if [ -n "$INTERFACE" ]; then
    echo "Placa de rede encontrada: $INTERFACE"
    ip link set $INTERFACE up
    udhcpc -i $INTERFACE -s /etc/udhcpc/default.script &
else
    echo "Nenhuma interface de rede encontrada."
fi
