- name: Gerar Imagem ISO com Limine
      run: |
        git clone https://github.com/limine-bootloader/limine.git --branch=v7.x-binary --depth=1
        make -C limine
        
        mkdir -p iso_root/boot iso_root/limine
        
        cp build/vmlinuz iso_root/ || echo "ERRO: vmlinuz não encontrado!"
        cp build/initramfs.img iso_root/ || echo "ERRO: initramfs.img não encontrado!"
        
        cp limine/limine-bios.sys limine/limine-bios-cd.bin limine/limine-uefi-cd.bin iso_root/
        
        echo "=== CONTEÚDO DA PASTA ISO_ROOT ==="
        ls -lh iso_root/
        
        cat <<EOF > iso_root/limine.conf
        timeout: 3
        /Carlinho-Linux (64-bit)
            protocol: linux
            kernel_path: boot:///vmlinuz
            initrd_path: boot:///initramfs.img
        EOF
        
        cp iso_root/limine.conf iso_root/boot/limine.conf
        cp iso_root/limine.conf iso_root/limine/limine.conf

        xorriso -as mkisofs -b limine-bios-cd.bin \
          -no-emul-boot -boot-load-size 4 -boot-info-table \
          --efi-boot limine-uefi-cd.bin \
          -efi-boot-part --efi-boot-image --protective-msdos-label \
          iso_root -o Carlinho-Linux.iso

        ./limine/limine bios-install Carlinho-Linux.iso
        
        # Mostra o tamanho final da ISO gerada
        ls -lh Carlinho-Linux.iso
